name: Lint

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Flake8 checkout
      run: |
        flake8
